config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :products

  resources :vendors
  resources :customers
  resources :carts
  resources :medorders
  resources :meddetails


  get '/vendor_listings', to:'vendors#vendor_id'
  post '/vendor_listings', to:'vendors#vendor_listing'
  post '/medorders', to: 'medorders#create '

  post   '/carts/new', to: 'carts#create'
  get   '/carts/new/ascending', to:'carts#sort', as: 'sort' #sort action
  get '/carts/new/details', to: 'carts#show'

   post '/order_details/', to: 'meddetails#create'
   get '/order_details/:id', to: 'meddetails#show'

 root 'products#index'



 
end

app/models/meddetail.rb
class Meddetail < ApplicationRecord
  belongs_to :medorder      #many to many
  belongs_to :product
  validates :total_quantity, numericality: {only_integer: true}, presence: true
  validates :medorder_id , presence: true
  validates :product_id , presence: true

end

app/controllers/meddetails_controller.rb
class MeddetailsController < ApplicationController
  def index


  end

  def new
    @meddetail = Meddetail.new
    @products = Product.all
    @customers= Customer.all
    @medorders =Medorder.all
    @medorder = Medorder.new
  end
    
def create

  @customer= Customer.last
  @products = Product.all
  @shopsession = Shopsession.last
  @cartitems = Cartitem.all.select { |item| item.shopsession_id == @shopsession.id}
 #performs select query on caritems that have the last shopsession id and returns an array
  
  @medorder = Medorder.new(customer_id: @customer.id)  
  @medorder.save! 
  #generate order after cart is finalised and customer goes to place order and make payment 


  #performs a mapping over the array to create orderdetails for each
  @cartitems.map do |item|
   @meddetail= Meddetail.create!(total_quantity: item.total_quantity, product_id: item.product_id, medorder_id: @medorder.id ) 
  end
   #generate final order details

   redirect_to  "/order_details/#{@medorder.id}"


end

  def show
    @customer=Customer.last
    @medorder = Medorder.last
    @cartitems = Cartitem.all 
    @meddetails = Meddetail.all
    #to get the total price for each product bought
    @price = []
    #getthe sum or total bill of customer.
    @sum = 0


  end

 

  
    




end

app/helpers/meddetails_helper.rb
module MeddetailsHelper
end

app/views/meddetails/_buy.html.erb
  <%= form_with  url:  '/meddetails/new' do |f|%> 

       <strong><%= f.label :product_id, "Enter product id" %></strong>
      <%= f.number_field :product_id, in: 1..100, step: 1 %>
      <br>
      <strong><%= f.label :total_quantity, "Quantity to buy" %></strong>
      <%= f.number_field :total_quantity, in: 1..100, step: 1 %>
 
           <%= f.submit "Add" %>

     <% end %>

app/views/meddetails/index.html.erb
<h1>Meddetails#index</h1>
<p>Find me in app/views/meddetails/index.html.erb</p>

app/views/meddetails/new.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

<br>
<br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort by product Id',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%= button_to "Place an order",  '/order_details', method: :get, class: 'check_order' %>


<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>

app/views/meddetails/show.html.erb
<%# Querying to get details of the order placed by customer %>

<p class="order" ><strong> Order Id: <%= @medorder.id%></strong></p>

<%# As there is one meddetails for many medorders, Meddetail is used to query based on its foreign key medorder_id.
Also, one medorder further has one customer for that order and it helps to locate the customer name using its
 customer_id foreign key. Here method chaining is used to filter and locate customer.%>

<%  @meddetails.each do |d|%>
   <% if @medorder.id == d.medorder_id  %>
     <p class="order_details"><strong>Customer name: <%= d.medorder.customer.name %> <%#= d.medorder.customer.id %> </strong></p
     <% break %>
   <% end %>
<% end %>


<div class="table-container">

<table class="t-style1">
   <tr>
      <th>Product id </th>
      <th>Product name</th>
      <th>Total Quantity(items)</th>
      <th>Unit Price</th>
      <th>Total Price($)</th>
   </tr>

<%# Meddetail references products through product_id and this foreign key is used
 to get product details like name, type or selling price %>

   <%  @meddetails.each do |d|%>
   <% if @medorder.id == d.medorder_id  %>
         <tr>
            <td><%=d.product_id %></td>
            <td><%= d.product.product_name %></td>
            <td><%= d.total_quantity %></td>
            <td><%= d.product.selling_price %></td>
            <td><%=  d.product.selling_price * d.total_quantity%></td>
            <% @price << d.product.selling_price * d.total_quantity  %>     
            <%# gets total price for all bought items in an array that helps to get the total sum %>   
      <% end %>
   <%end %>

</table>

    <%  @price.each {|price| @sum= @sum+ price } %>
<p class="order_details1"><strong>Total Bill =>  $<%= @sum %>  </strong></p

</div>


<%= button_to 'Pay here', products_path, class: 'btn2' %>

      
                  

app/views/meddetails/sort.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

    <br>
    <br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort by product Id',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%= button_to "Check details of order",  '/order_details', method: :get, class: 'check_order' %>


<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>