config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :products

  resources :vendors
  resources :customers
  resources :carts
  resources :medorders
  resources :meddetails


  get '/vendor_listings', to:'vendors#vendor_id'
  post '/vendor_listings', to:'vendors#vendor_listing'
  post '/medorders', to: 'medorders#create '

  post   '/carts/new', to: 'carts#create'
  get   '/carts/new/ascending', to:'carts#sort', as: 'sort' #sort action
  get '/carts/new/details', to: 'carts#show'

   post '/order_details/', to: 'meddetails#create'
   get '/order_details/:id', to: 'meddetails#show'

 root 'products#index'



 
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :medorders  #one to many relation with orders
    validates :name , presence: true,  uniqueness: true
    validates :email , presence: true,  uniqueness: true
    validates :user_id , presence: true
    has_many :shopsessions
    belongs_to :user
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  
  end

  def new 
    @customer = Customer.new 
  end

  def create
  
    @customer= Customer.new(customer_params) 
  #new customer is created and saved and redirected to show the customer info. 
    if @customer.save!
      redirect_to @customer
     
    else 
    render :new, status: :unprocessable_entity
  end
end




def show

  @customer = Customer.find(params[:id])
  
  if @customer.nil?
   render  :new
  end
  
end

      
         
def edit
  @customer = Customer.find(params[:id])
  #finds customer with matching param id so that customer can edit info
end


def update
  @customer= Customer.find(params[:id])

  if @customer.update(customer_params)

    redirect_to  customer_path(@customer)
  else
    render :edit, status: :unprocessable_entity
  end
end





  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to   new_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :user_id)
    #validates and permits the paramters for mass assignment.
  end 


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<h1>Customers#index</h1>
<p>Find me in app/views/customers/index.html.erb</p>


<%# Customer has many orders %>
<% #@customers= Customer.eager_load(:medorders) %>

<table>
<tr><th>Name</th></tr>

<tr>
<td><%#= c.name %></td>
<td><%#= c.medorders.customer_id %></td>

</tr>





</table>

app/views/customers/new.html.erb
<p class="user-id">User-ID:   <%= current_user.id %></p>   <%#specifically this user refers to customers%>
<h3 class="headline ">Enter new customer details</h3>

<%= form_with  model: @customer ,class: 'customer-form' do |f|%>

    <p style ="padding-top: 30px;"> <strong><%= f.label :name, "Enter your name" %></strong></p>
      <%= f.text_field :name %><br>
       <% @customer.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
      <% end %><br>

    <p style ="padding-top: 30px;">  <strong><%= f.label :user_id, "User ID" %></strong></p>
      <%= f.number_field :user_id, in: 1..100, step: 1 %><br>
       <% @customer.errors.full_messages_for(:user_id).each do |message| %>
          <div><%= message %></div>
      <% end %>
    <p style ="padding-top: 30px;">  <strong><%= f.label :email, "Your Email" %></strong></p>
      <%= f.text_field :email %><br>
       <% @customer.errors.full_messages_for(:email).each do |message| %>
          <div><%= message %></div>
      <% end %>
    <p style=" font-size:1rem;"><strong> <%= f.submit "Register",class: 'register-customer' %></strong><p>

<% end %>
   <br>

<%= button_to 'Already Registered', new_medorder_path ,method: :get, class: 'btn'%>
<br>

<%#= button_to 'Back', products_path ,method: :get, class: 'back-btn'%>

app/views/customers/show.html.erb
 

<table class="customer-table">
 <tr>
   <th><strong>Customer Name: </strong></th>
   <th><strong>Customer Email: </strong></th>
</tr>
<tr>
  <td><%= @customer.name %></td>
  <td><%=  @customer.email %> </td>
</tr>


</table>
 
<div> 


<%if current_user.id == @customer.user_id %>
<%#the id is added to check whether the customer signed in is same as the customer id %>
<%# Though in reality the customer sign in will automatically update the customer table with name email and id.But since 
website has both the vendor and buyer option, the option for adding customer id is given which gets added through post request. %>

<%= button_to 'Edit information',   edit_customer_path, method: :get, class: "btn2" %>
<%= button_to 'Back',   new_customer_path, method: :get, class: "btn2" %>

 <ul> 
 <li><%= button_to "Delete", @customer,
                   method: :delete ,
                   class: "btn2",
                  data: { confirm: "Are you sure?" } %> </li>
</ul> 

<%end %>