config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :products

  resources :vendors
  resources :customers
  resources :carts
  resources :medorders
  resources :meddetails


  get '/vendor_listings', to:'vendors#vendor_id'
  post '/vendor_listings', to:'vendors#vendor_listing'
  post '/medorders', to: 'medorders#create '

  post   '/carts/new', to: 'carts#create'
  get   '/carts/new/ascending', to:'carts#sort', as: 'sort' #sort action
  get '/carts/new/details', to: 'carts#show'

   post '/order_details/', to: 'meddetails#create'
   get '/order_details/:id', to: 'meddetails#show'

 root 'products#index'



 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 
  attr_reader :cartsum
  
  def index
    @products = Product.all
    @customer= Customer.last
    @shopsession = Shopsession.last 
    @cartitems= Cartitem.all
    @price = []
    @sum=0
   #displays the current cart for current shopssession with all products checked in and  other details.
  
  end

 def new
  @cartsum = 0
  @cartitem= Cartitem.new
  @products = Product.all
  @shopsession = Shopsession.last
  @cartitems =Cartitem.all

  #everytime new cartitem is added, the loop checks for matching shopsession id and
#  updatesthe cartsum
for cartitem in @cartitems
  if cartitem.shopsession_id == @shopsession.id 
    @cartsum += cartitem.total_quantity
  end
end


 

 end

 def create
  
  @customer= Customer.last
  @shopsession = Shopsession.last
  @products = Product.all
  @cartitem = Cartitem.new(shopsession_id: @shopsession.id, total_quantity: params[:total_quantity],
  product_id: params[:product_id])
  @cartitem.save!

#creating new cartitem with post request from _buy partial.
  redirect_to new_cart_path


   
  

 end


 def edit

  @cartitem= Cartitem.find(params[:id])
  @products = Product.all 
 end



 def update
  @customer= Customer.last
  @shopsession = Shopsession.last
  @products = Product.all

   @cartitem = Cartitem.new(shopsession_id: @shopsession.id, total_quantity: params[:total_quantity],
  product_id: params[:product_id])
  @cartitem.save!


 
 end

 def show
  @customer= Customer.last
  @shopsession = Shopsession.last
  @cartitems = Cartitem.all
 

 end


 def sort

  @products= Product.order(:product_name) #sort ascending order all products using product id

  end

 

    # def params_require
    #   params.require(:cartitem).permit([]:product_id,:total_quantity)

    # end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_buy.html.erb
  <%= form_with  url:  '/carts/new' do |f|%> 

       <strong><%= f.label :product_id, "Enter product id" %></strong>
      <%= f.number_field :product_id, in: 1..100, step: 1 %>
      <br>
      <strong><%= f.label :total_quantity, "Quantity to buy" %></strong>
      <%= f.number_field :total_quantity, in: 1..100, step: 1 %>
 
           <%= f.submit "Add" %>

     <% end %>

app/views/carts/cart.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

<br>
<br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort A-Z',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%= button_to "View Cart",'/carts', method: :get, class: 'check_order' %>
 <p style="position:fixed; top: 50px; right: 30px;background-color: rgb(61, 103, 109);color: white; padding:5px;">Cart Quantity(<%= @cartitem.total_quantity%>)</p>
 
<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>

app/views/carts/edit.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

<br>
<br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort by product Id',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%#= button_to "Place an order",  '/order_details', method: :get, class: 'check_order' %>
<%= button_to "View Cart",  carts_path, method: :get, class: 'check_order' %>


<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>

app/views/carts/index.html.erb
<%# Querying to get details of the order placed by customer %>

<p class="order" ><strong> Cart</strong></p>

<%# As there is one meddetails for many medorders, Meddetail is used to query based on its foreign key medorder_id.
Also, one medorder further has one customer for that order and it helps to locate the customer name using its
 customer_id foreign key. Here method chaining is used to filter and locate customer.%>

<%  @cartitems.each do |d|%>
   <% if @shopsession.id == d.shopsession_id  %>
     <p class="order_details"><strong>Customer name: <%= d.shopsession.customer.name %> <%#= d.medorder.customer.id %> </strong></p
     <% break %>
   <% end %>
<% end %>


<div class="table-container">

<table class="t-style1">
   <tr>
      <th>Product id </th>
      <th>Product name</th>
      <th>Quantity(items)</th>
      <th>Unit Price</th>
      <th>Total Price($)</th>
   </tr>

<%# Meddetail references products through product_id and this foreign key is used
 to get product details like name, type or selling price %>

   <%  @cartitems.each do |d|%>
    <% if @shopsession.id == d.shopsession_id  %>
         <tr>
            <td><%=d.product_id %></td>
            <td><%= d.product.product_name %></td>
            <td><%= d.total_quantity %></td>
            <td><%= d.product.selling_price %></td>
            <td><%=  d.product.selling_price * d.total_quantity%></td>
            <% @price << d.product.selling_price * d.total_quantity  %>     
            <%# gets total price for all bought items in an array that helps to get the total sum %>   
      <% end %>
   <%end %>

</table>

    <%  @price.each {|price| @sum= @sum+ price } %>
<p class="order_details1"><strong>Total Bill =>  $<%= @sum %>  </strong></p

</div>


<%= button_to 'Place Order & Pay', '/order_details', class: 'btn2' %>
<%#= button_to 'Edit Cart', edit_cart_path, class: 'btn2' %>

app/views/carts/new.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

<br>
<br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort A-Z',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%= button_to "View Cart",'/carts', method: :get, class: 'check_order' %>


<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>

app/views/carts/sort.html.erb
<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

   
     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
            <strong>Product Id: </strong> 
            <%= product.id %>

    <br>
    <br>
      <%= render "buy" %>
     


     
</div>
<% end %>

</div>



<%= button_to 'Sort A-Z',  sort_path ,method: :get, class: 'sort-btn'%>
<br>
<%= button_to "View cart", carts_path, method: :get, class: 'check_order' %>


<%= button_to 'Back', new_medorder_path ,method: :get, class: 'back-btn'%>