config/routes.rb
Rails.application.routes.draw do


  devise_for :users


  resources :products

  resources :vendors
  resources :customers
  resources :carts
  resources :medorders
  resources :meddetails


  get '/vendor_listings', to:'vendors#vendor_id'
  post '/vendor_listings', to:'vendors#vendor_listing'
  post '/medorders', to: 'medorders#create '

  post   '/carts/new', to: 'carts#create'
  get   '/carts/new/ascending', to:'carts#sort', as: 'sort' #sort action
  get '/carts/new/details', to: 'carts#show'

   post '/order_details/', to: 'meddetails#create'
   get '/order_details/:id', to: 'meddetails#show'

 root 'products#index'



 
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :vendor
    has_many :meddetails    
    validates :vendor_id, numericality: {only_integer: true}, presence: true
    validates :product_name , presence: true, uniqueness: true
    validates :product_type , presence: true
    validates :product_description , presence: true
    validates :selling_price , presence: true
    validates :image , presence: true
    has_one_attached :image

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
    

    if @product.nil?
     render  :new
    end
    
  end
  def new
      @product = Product.new
  end

  def create
  
      
    @product= Product.new(product_params) 
  if @product.save 
      redirect_to  product_path(@product)
    else 
    render :new, status: :unprocessable_entity
  end
 
     

  end

  def edit
    @product = Product.find(params[:id])

  end


  def update
    @product= Product.find(params[:id])

    if @product.update(product_params)
      redirect_to  product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end





  
  private
  def product_params
    params.require(:product).permit(:product_name, :product_type, :product_description, :vendor_id, :selling_price, :image)
  end 
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1 class="headline">Add Products to sell</h1>

<div class="vendor_btns">
<%= button_to 'Add new vendor info', new_vendor_path, method: :get, :class => "btn3 add_vendor" %>
<%#= button_to 'Existing Member info', vendor_path, method: :get, :class => "btn3" %>
</div>




<%= form_with model: @product do |form| %>
  <div class="container-flex">

 

  <div class="field">
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
    <% @product.errors.full_messages_for(:product_name).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

   <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image,  accept: 'image/png, image/jpeg, image/jpg' %>
    <% @product.errors.full_messages_for(:image).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>
  
  <div class="field">
    <%= form.label :product_type %><br>
    <%= form.text_field :product_type %>
   <% @product.errors.full_messages_for(:product_type).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :product_description %><br>
    <%= form.text_area :product_description %>
      <% @product.errors.full_messages_for(:product_description).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :vendor_id, 'Vendor Id' %><br>
    <%= form.number_field :vendor_id, in: 1..100,  step: 1 %>
      <% @product.errors.full_messages_for(:vendor_id).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :selling_price %><br>
   <%= form.number_field :selling_price, in: 1.0..130.0,  step: 0.1 %>
     <% @product.errors.full_messages_for(:selling_price).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>
  </div>

  <div class="form_btn">
    <%= form.submit 'Update Product' %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= image_tag 'gear.png', alt: 'css',:class => "gear_rotating"%>

<%= button_to 'Buy Med Products',  new_customer_path, method: :get, class: "products_option"%>


<br>
<br>
<%= button_to 'Sell as a vendor',  new_vendor_path, method: :get, class:  "vendor_option" %>
<p class="user-id">User-ID:   <%= current_user.id %></p>  <%#specifically this user refers to customers%>

<h1 style="text-align:left;text-decoration: underline;position:fixed; margin-top:13rem; color:rgba(24, 24, 24, 0.809);">MedPro</h1>


<div class="products_container">

<% @products.each do |product| %>
<div class="inner-container">

     <div>
      <% if  product.image.attached? %>
        <%= image_tag url_for(product.image), width: '250px', class: "product-image"%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.name %> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %> 
    </div>


     

  
     
</div>
<% end %>

</div>

app/views/products/new.html.erb
<h1 class="headline">Add Products to sell</h1>

<div class="vendor_btns">

<%#= button_to 'Existing Member info', vendor_path, method: :get, :class => "btn3" %>
</div>



<%= form_with model: @product do |form| %>
  <div class="container-flex">
 
  <div class="field">
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
    <% @product.errors.full_messages_for(:product_name).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>
   <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image, accept: 'image/png, image/jpeg, image/jpg' %>
    <% @product.errors.full_messages_for(:image).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>
  <div class="field">
    <%= form.label :product_type %><br>
    <%= form.text_field :product_type %>
   <% @product.errors.full_messages_for(:product_type).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :product_description %><br>
    <%= form.text_area :product_description %>
      <% @product.errors.full_messages_for(:product_description).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :vendor_id, 'Vendor Id' %><br>
    <%= form.number_field :vendor_id, in: 1..100,  step: 1 %>
      <% @product.errors.full_messages_for(:vendor_id).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>

  <div class="field">
    <%= form.label :selling_price %><br>
   <%= form.number_field :selling_price, in: 1.0..130.0,  step: 0.1 %>
     <% @product.errors.full_messages_for(:selling_price).each do |message| %>
          <div><%= message %></div>
      <% end %>
  </div>


   <div class="field">
    <%= form.submit 'Save' %>
    </div>
  </div>
<% end %>



<%= button_to 'Back', new_vendor_path, method: :get, :class => "btn" %>

app/views/products/show.html.erb
<div class="medical_products">
    <h1 class="headline">The Product</h1>
    <div>
      <% if  @product.image.attached? %>
        <%= image_tag url_for(@product.image), width: '250px'%>
        <% end %>
    </div>
    <div>
        <strong>Name: </strong>
        <%= @product.product_name %>
    </div>

    <div>
        <strong>Type: </strong>
        <%= @product.product_type %>
    </div>

    <div>
        <strong>Description: </strong>
        <%= @product.product_description %>
    </div>
    <div>
        <strong>Price: </strong>
      $ <%= @product.selling_price %></p> 
    </div>
    <div>
        <strong>Seller's Address: </strong>
          <%  @vendor = Vendor.find(@product.vendor_id) %>
       <%= @vendor.city %>, <%= @vendor.state %>, <%= @vendor.zipcode %> 
    </div>
      
 </div>



<%= button_to 'Edit information',   edit_product_path, method: :get, class: "btn2" %>
<br>
<%= button_to 'Back',   new_product_path, method: :get, class: "btn" %>
<br>
<br>
<ul>
 <li><%= link_to "Destroy", product_path(@product),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>